env: DOCKER_COMPOSE_VERSION: 1.8.0
sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - docker

before_install:
  - docker-compose --version




