sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - docker

before_install:
  - docker build -t ggavarra/micfin-app

script:
  - docker run ggavarra/micfin-app npm test -- --coverage



